### ISSUE TITLE
Card Creation API Test

### ISSUE THREAD

**Issue by simonmika** [pax2pay/client-js#1]
basic test protocol:

```
foreach provider:
	foreach card type: (neccessitates card types api call)
		foreach currency: (neccessitates funding account api call)
			make basic card
			change card state/limits if provider allows
```

- [x] #3
- [x] #4
- [x] #5
- [x] #6

**Comment by lucy-meachem** [comment]
provider: fake (do first for ease), conferma, wex, ixaris, modulr
card type: https://docs-internal.pax2pay.com/#operation/getAllCardTypesForProvider
currencies: https://docs-internal.pax2pay.com/#operation/searchFundingAccounts (for provider)

basic card create: https://docs-internal.pax2pay.com/#operation/createCard
amend https://docs-internal.pax2pay.com/#operation/amendCard_1 (modulr/ixaris only)
states https://docs-internal.pax2pay.com/#operation/freezeCard https://docs-internal.pax2pay.com/#operation/thawCard https://docs-internal.pax2pay.com/#operation/cancelCard_1 (only some providers)
